server:
  port: 8102

info:
  app:
    description: Quotation Service
    name: Quotation Service
    version: 1.0.0

app:
  quotation:
    expiryTime: 1440
  customerSrvUrl: http://localhost:3000
  productSrvUrl: http://localhost:3000

spring:
  application:
    name: quotation-srv
  datasource:
    url: jdbc:h2:mem:quotation
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true